feat: 11 add shoppingcart
EduarfF/book-store pull request #12
Opened 2024-05-22 08:46 UTC by EduarfF

2024-05-22 14:39 UTC, bodya4243 approved these changes
Well done

2024-05-23 07:50 UTC, karma-o requested changes
We need to do some improvements to your solutin

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/controller/ShoppingCartController.java
> +    @PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
you can use `hasAnyRole()`

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/controller/ShoppingCartController.java
> +            @PathVariable Long cartItemsId,
```suggestion
            @PathVariable Long cartItemId,
```

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/dto/cartitem/CreateCartItemRequestDto.java
> +    private int quantity;
what if user sends you null?

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/dto/cartitem/UpdateCartItemDto.java
> +    private int quantity;
same here

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/model/CartItem.java
> +@Setter
do not forget about equals & hashcode & toString

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/model/CartItem.java
> +@SQLRestriction(value = "is_deleted=false")
wouldn't say that we need a soft delete for cart items, does not seem like a very important an irreplaceable information for me, and user can update their cart multiple times, remove some books from it several times a day, should we store all that? I'd say no

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/model/ShoppingCart.java
> +@SQLRestriction(value = "is_deleted=false")
I do not think we will ever delete a shopping cart, maybe if we want to delete a user, but I think that would be expected if we delete the user - the cart will be emptied and deleted as well, but that is more of a business question, so up to you

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/service/cartitem/CartItemServiceImpl.java
> +        cartItemRepository.deleteAll(cartItem);
here we do not need to check any cart item ids, so I think something like that would be better
```suggestion
        cartItemRepository.deleteAllByShoppingCartId(shoppingCart.getId());
```

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/service/cartitem/CartItemServiceImpl.java
> +    }
move that to shoppingCartService

2024-05-23 07:50 UTC, karma-o commented on src/main/java/org/example/springbootintro/service/shoppingcart/ShoppingCartServiceImpl.java
> +    }
we do not need to wrap 1 service methods into another one, we can just use them directly

2024-05-24 07:31 UTC, karma-o approved these changes
Nice!

2024-05-24 07:32 UTC, merged