feat: 12 add order
EduarfF/book-store pull request #13
Opened 2024-05-24 13:08 UTC by EduarfF

2024-05-27 12:56 UTC, andrii-hoienko requested changes
Nice, left some comments

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/controller/OrderController.java
> +        return orderItemService.getAll(orderId, pageable);
Please make sure that one user can not access order data of different user

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/dto/order/CreateOrderRequestDto.java
> +    @NotBlank(message = "Shipping address ca not be blank")
NotBlank already includes NotNull

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/dto/order/CreateOrderRequestDto.java
> +    private String shippingAddress;
add length validation to be aligned with db

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/service/order/OrderServiceImpl.java
> +        order.setOrderItems(orderItems);
Move order creation logic to separate method

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/service/order/OrderServiceImpl.java
> +    private static BigDecimal getSumOfAllItems(Set<OrderItem> orderItems) {
```suggestion
    private static BigDecimal getTotal(Set<OrderItem> orderItems) {
```

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/service/order/OrderServiceImpl.java
> +    }
Could be done using streams

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/service/order/OrderServiceImpl.java
> +    private static Set<OrderItem> getOrderItems(ShoppingCart shoppingCart, Order order) {
```suggestion
    private Set<OrderItem> getOrderItems(ShoppingCart shoppingCart, Order order) {
```

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/service/orderitem/OrderItemServiceImpl.java
> +    public List<OrderItemDto> getAll(Long id, Pageable pageable) {
```suggestion
    public List<OrderItemDto> getAll(Long orderId, Pageable pageable) {
```

2024-05-27 12:56 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/service/orderitem/OrderItemServiceImpl.java
> +        return orderItemMapper.toDto(orderItem);
```suggestion
        return orderItemRepo.find(orderId, userId, orderItemId)
```

2024-05-28 09:35 UTC, yevheniisynytsia approved these changes

2024-05-28 09:35 UTC, yevheniisynytsia commented on src/main/java/org/example/springbootintro/model/Order.java
> +    @ManyToOne
please use LAZY fetch type and it is better to add this even if it's default fetch type for the annotation

2024-05-28 09:35 UTC, yevheniisynytsia commented on src/main/java/org/example/springbootintro/service/orderitem/OrderItemServiceImpl.java
> +                );
```suggestion
                        "Can not find order item with id: " + itemId));
```

2024-05-28 10:56 UTC, merged