Add docker
EduarfF/book-store pull request #14
Opened 2024-05-27 15:25 UTC by EduarfF

2024-05-27 17:49 UTC, HAIOVYI approved these changes
GJ

2024-05-28 13:11 UTC, andrii-hoienko requested changes
Please check PR before pushing to review, you should make self review first, and then send to mentor`s review

2024-05-28 13:11 UTC, andrii-hoienko commented on .gitignore
> +.env
```suggestion
.env

```

2024-05-28 13:46 UTC, andrii-hoienko approved these changes
Nice!

2024-05-28 14:19 UTC, merged