feat: 3 add jpa repository and some methods
EduarfF/book-store pull request #4
Opened 2024-04-25 15:21 UTC by EduarfF

2024-04-25 17:24 UTC, k0sm0naft requested changes
Not bad, left few comments.

2024-04-25 17:24 UTC, k0sm0naft commented on src/main/java/org/example/springbootintro/controller/BookController.java
> +@RequestMapping(value = "apibooks")
You can leave '/books'. And '/api' move to application.properties `server.servlet.context-path=/api`

2024-04-25 17:24 UTC, k0sm0naft commented on src/main/java/org/example/springbootintro/controller/BookController.java
> +    @ResponseStatus(HttpStatus.CONTINUE)
You are sure in this status? Maybe better chose something else.

2024-04-25 17:24 UTC, k0sm0naft commented on src/main/java/org/example/springbootintro/controller/BookController.java
> +    @PutMapping("/{id}")
You can add statuses to other methods too.

2024-04-25 17:24 UTC, k0sm0naft commented on src/main/java/org/example/springbootintro/model/Book.java
> +@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id=?")
You should add restriction for use soft-de;ete.
```suggestion
@SQLDelete(sql = "UPDATE books SET is_deleted = true WHERE id=?")
@SQLRestriction(value = "is_deleted = false")
```

2024-04-25 17:24 UTC, k0sm0naft commented on src/main/java/org/example/springbootintro/service/book/BookServiceImpl.java
> +        bookRepository.deleteById(id);
It is work, but what will be if u use wrong id?

2024-04-25 17:24 UTC, k0sm0naft commented on src/main/resources/db/changelog/changes/01-create-books-table.yml
> +                  type: decimal
```suggestion
                  type: decimal(12, 2)
```

2024-04-25 17:24 UTC, k0sm0naft commented on src/main/java/org/example/springbootintro/service/book/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(book));
What will be, if ID not exist, or you try to use ISBN that already exist, or your ISBN was soft-deleted, and you try to add it one more time?

2024-04-26 08:02 UTC, karma-o requested changes
some very minor comments only

2024-04-26 08:02 UTC, karma-o commented on src/main/java/org/example/springbootintro/service/book/BookServiceImpl.java
> +    private void bookExist(Long id) {
```suggestion
    private void checkIfBookExists(Long id) {
```

2024-04-26 08:02 UTC, karma-o commented on src/main/java/org/example/springbootintro/service/book/BookServiceImpl.java
> +        if (bookRepository.findById(id).isEmpty()) {
we can make our db request lighter since we do not use the book data that we fetch - we can just use `repo.existsById()` instead of `find` which will just count the resulting rows making a request a bit faster
```suggestion
        if (bookRepository.existsById()) {
```

2024-04-26 08:02 UTC, karma-o commented on src/main/resources/db/changelog/changes/01-create-books-table.yml
> +                    nullable: false
```suggestion
                    nullable: false

```

2024-04-26 08:02 UTC, karma-o commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changes/01-create-books-table.yml
```suggestion
      file: db/changelog/changes/01-create-books-table.yml

```

2024-04-26 13:28 UTC, andrii-hoienko approved these changes
Good job!

2024-04-26 14:06 UTC, merged