feat: 4 add criteria query for books(title, author)
EduarfF/book-store pull request #5
Opened 2024-04-26 17:03 UTC by EduarfF

2024-04-29 10:19 UTC, yevheniisynytsia requested changes
Well done! Almost there!

2024-04-29 10:19 UTC, yevheniisynytsia commented on src/main/java/org/example/springbootintro/repository/book/BookSpecificationBuilder.java
> +    private SpecificationProviderManager<Book> bookSpecificationProviderManager;
let's pass it as a constructor parameter

2024-04-29 10:19 UTC, yevheniisynytsia commented on src/main/java/org/example/springbootintro/repository/book/spec/AuthorSpecificationProvider.java
> +        return "author";
let's make it a `public` constant

2024-04-29 10:19 UTC, yevheniisynytsia commented on src/main/java/org/example/springbootintro/repository/book/BookSpecificationBuilder.java
> +                    .getSpecificationProvider("author")
and reuse here as well

2024-04-29 10:34 UTC, yevheniisynytsia requested changes

2024-04-29 10:34 UTC, yevheniisynytsia commented on src/main/java/org/example/springbootintro/repository/book/BookSpecificationBuilder.java
> +    }
use lombok please

2024-04-29 10:34 UTC, yevheniisynytsia commented on src/main/java/org/example/springbootintro/repository/book/BookSpecificationBuilder.java
> +                    .getSpecificationProvider("author")
please make your constant from AuthorSpecificationProvider public and use it here

2024-04-29 10:34 UTC, yevheniisynytsia commented on src/main/java/org/example/springbootintro/repository/book/spec/TitleSpecificationProvider.java
> +        return "title";
please add constant here as well

2024-05-01 10:29 UTC, karma-o approved these changes
Nice!

2024-05-01 11:54 UTC, merged