feat: 6 add pagination and swagger
EduarfF/book-store pull request #7
Opened 2024-05-03 11:47 UTC by EduarfF

2024-05-06 13:26 UTC, andrii-hoienko requested changes
Nice, left minor comments

2024-05-06 13:26 UTC, andrii-hoienko commented on src/main/java/org/example/springbootintro/controller/BookController.java
>      public List<BookDto> search(@Valid BookSearchParametersDto bookSearchParametersDto) {
Add pageable here as well

2024-05-07 08:06 UTC, karma-o approved these changes
Approved with a couple more suggestions from me

2024-05-07 08:06 UTC, karma-o commented on src/main/java/org/example/springbootintro/controller/BookController.java
> +            @Valid BookSearchParametersDto bookSearchParametersDto
having a search parameters documentation is usually very useful for the whole team

2024-05-07 08:06 UTC, karma-o commented on src/main/java/org/example/springbootintro/controller/BookController.java
>                                @RequestBody @Valid CreateBookRequestDto bookDto
The same goes for the request DTOs, we can also add some description for some of those fields as well, like defining what formats of ISBN we accept for example

2024-05-07 16:02 UTC, merged